export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as Verify } from './Verify'
export { default as ProtectedRoute } from './ProtectedRoute'
export { default as ForgotPassword } from './ForgotPassword'
export { default as ResetPassword } from './ResetPassword'
